# Generated by Django 5.0.7 on 2024-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
