# Generated by Django 5.0.7 on 2024-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_department_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
