# Generated by Django 5.1 on 2024-08-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0002_coursehour_lesson_course_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course_hour",
        ),
        migrations.AddField(
            model_name="lesson",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                default="Monday",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="end_time",
            field=models.TimeField(default="17:00"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.DeleteModel(
            name="CourseHour",
        ),
    ]
