# Generated by Django 5.1 on 2024-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0003_remove_lesson_course_hour_lesson_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                default="Monday",
                max_length=9,
            ),
        ),
    ]
