# Generated by Django 5.1 on 2024-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0004_alter_lesson_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
