# Generated by Django 5.0.7 on 2024-08-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
