# Generated by Django 5.0.7 on 2024-08-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
