# Generated by Django 5.1 on 2024-08-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_alter_lesson_day_of_week_alter_lesson_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
