# Generated by Django 5.1 on 2024-08-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0011_alter_lesson_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
    ]
