# Generated by Django 5.1 on 2024-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0012_remove_lesson_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False, unique=True),
        ),
    ]
