# Generated by Django 5.1 on 2024-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0014_alter_lesson_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
