# Generated by Django 5.1 on 2024-08-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0016_populate_lesson_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
    ]
