# Generated by Django 5.1 on 2024-08-26 08:13

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Lesson = apps.get_model('baseapp', 'Lesson')
    for lesson in Lesson.objects.all():
        lesson.slug = slugify(lesson.title)
        lesson.save()


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0018_lesson_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slug),
        ]
