# Generated by Django 5.1 on 2024-08-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0019_populate_slug_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="category",
            new_name="department",
        ),
    ]
