# Generated by Django 5.1 on 2024-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0020_rename_category_lesson_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("courses", models.CharField(max_length=250)),
            ],
        ),
    ]
