# Generated by Django 5.1 on 2024-09-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0022_studentcareer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recommendation",
        ),
    ]
