# Generated by Django 5.1 on 2024-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0023_delete_recommendation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentCareer",
        ),
    ]
