# Generated by Django 5.1 on 2024-08-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0004_alter_student_department_of_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountapp.teacher",
            ),
        ),
    ]
