# Generated by Django 5.1 on 2024-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0005_student_adviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.IntegerField(default=1),
        ),
    ]
