# Generated by Django 5.1 on 2024-08-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0007_teacher_advisee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="adviser",
        ),
    ]
