# Generated by Django 5.1 on 2024-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0008_remove_student_adviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="adviser",
            field=models.BooleanField(default=False),
        ),
    ]
