# Generated by Django 5.1 on 2024-08-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0009_student_adviser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountapp.teacher",
            ),
        ),
    ]
