# Generated by Django 5.1 on 2024-08-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0010_alter_student_adviser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="advisee",
        ),
    ]
