# Generated by Django 5.1 on 2024-08-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0011_remove_teacher_advisee"),
        ("baseapp", "0002_coursehour_lesson_course_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentlesson",
            name="lessons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="baseapp.lesson",
            ),
        ),
    ]
