# Generated by Django 5.1 on 2024-08-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0012_alter_studentlesson_lessons"),
        ("baseapp", "0002_coursehour_lesson_course_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="adviser",
        ),
        migrations.AlterField(
            model_name="studentlesson",
            name="lessons",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="baseapp.lesson"
            ),
        ),
    ]
