# Generated by Django 5.1 on 2024-08-19 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0013_remove_student_adviser_alter_studentlesson_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accountapp.teacher",
            ),
        ),
    ]
