# Generated by Django 5.1 on 2024-08-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0014_student_adviser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student_ects",
            new_name="acts",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="department_of_student",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="student_lessons",
            new_name="lessons",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="lesson_of_teacher",
            new_name="lessons",
        ),
    ]
