# Generated by Django 5.1 on 2024-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0015_rename_student_ects_student_acts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
