# Generated by Django 5.1 on 2024-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0016_student_is_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="year",
        ),
    ]
