# Generated by Django 5.1 on 2024-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0017_remove_student_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
