# Generated by Django 5.1 on 2024-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0018_student_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(
                default="photos/default-profile-photo.jpg", upload_to="photos/"
            ),
        ),
    ]
