# Generated by Django 5.1 on 2024-08-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="message_of_student",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="message_of_teacher",
            new_name="teacher",
        ),
    ]
