# Generated by Django 5.0.7 on 2024-08-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_of_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lesson_of_teacher',
            field=models.ManyToManyField(blank=True, null=True, to='baseapp.lesson'),
        ),
    ]
