# Generated by Django 5.0.7 on 2024-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
        ('teacherapp', '0002_alter_customuser_department_of_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lesson_of_teacher',
            field=models.ManyToManyField(blank=True, to='baseapp.lesson'),
        ),
    ]
