# Generated by Django 5.1 on 2024-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0002_rename_message_of_student_contact_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCareer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interested_domain", models.CharField(max_length=100)),
                ("project", models.CharField(max_length=100)),
                (
                    "python",
                    models.CharField(
                        choices=[
                            ("Weak", "Weak"),
                            ("Average", "Average"),
                            ("Strong", "Strong"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "java",
                    models.CharField(
                        choices=[
                            ("Weak", "Weak"),
                            ("Average", "Average"),
                            ("Strong", "Strong"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "sql",
                    models.CharField(
                        choices=[
                            ("Weak", "Weak"),
                            ("Average", "Average"),
                            ("Strong", "Strong"),
                        ],
                        max_length=7,
                    ),
                ),
                ("future_career", models.CharField(max_length=100)),
            ],
        ),
    ]
