# Generated by Django 5.1 on 2024-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0003_studentcareer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcareer",
            name="interested_domain",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentcareer",
            name="project",
            field=models.TextField(max_length=100),
        ),
    ]
