# Generated by Django 5.1 on 2024-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0004_alter_studentcareer_interested_domain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcareer",
            name="future_career",
        ),
        migrations.RemoveField(
            model_name="studentcareer",
            name="interested_domain",
        ),
        migrations.RemoveField(
            model_name="studentcareer",
            name="java",
        ),
        migrations.RemoveField(
            model_name="studentcareer",
            name="project",
        ),
        migrations.RemoveField(
            model_name="studentcareer",
            name="python",
        ),
        migrations.RemoveField(
            model_name="studentcareer",
            name="sql",
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="algorithms_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="certificate",
            field=models.TextField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="coding_skills",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="communication_skills_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="computer_arc_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="computer_network_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="electronics_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="interested_subject",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="is_in_teams",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="is_introvert",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="is_self_learning",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="math_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="operating_sys_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="programming_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="software_eng_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="studentcareer",
            name="suggested_career",
            field=models.TextField(default="", max_length=100),
        ),
    ]
