# Generated by Django 5.1 on 2024-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0006_careersuggestion_delete_studentcareer"),
    ]

    operations = [
        migrations.AddField(
            model_name="careersuggestion",
            name="model_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="algorithms_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="coding_skills",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="communication_skills_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="computer_arc_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="computer_network_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="electronics_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="is_in_teams",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="is_introvert",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="is_self_learning",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="math_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="operating_sys_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="programming_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="software_eng_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
