# Generated by Django 5.0.7 on 2024-08-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0006_rename_user_student_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='user',
        ),
    ]
