# Generated by Django 5.0.7 on 2024-08-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_rename_student_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_ects',
            field=models.IntegerField(default=0),
        ),
    ]
