# Generated by Django 5.1 on 2024-09-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0007_careersuggestion_model_blob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersuggestion",
            name="certificate",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="interested_subject",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="suggested_career",
            field=models.TextField(max_length=100),
        ),
    ]
