# Generated by Django 5.0.7 on 2024-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_lesson_capacity'),
        ('teacherapp', '0008_student_student_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_lessons',
            field=models.ManyToManyField(blank=True, to='baseapp.lesson'),
        ),
    ]
