# Generated by Django 5.1 on 2024-09-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0008_alter_careersuggestion_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careersuggestion",
            name="model_blob",
        ),
    ]
