# Generated by Django 5.1 on 2024-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0009_remove_careersuggestion_model_blob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersuggestion",
            name="certificate",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="careersuggestion",
            name="interested_subject",
            field=models.CharField(max_length=100),
        ),
    ]
