# Generated by Django 5.1 on 2024-09-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0010_alter_careersuggestion_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careersuggestion",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="careersuggestion",
            name="interested_subject",
        ),
        migrations.RemoveField(
            model_name="careersuggestion",
            name="is_in_teams",
        ),
        migrations.RemoveField(
            model_name="careersuggestion",
            name="is_introvert",
        ),
        migrations.RemoveField(
            model_name="careersuggestion",
            name="is_self_learning",
        ),
        migrations.RemoveField(
            model_name="careersuggestion",
            name="suggested_career",
        ),
    ]
