# Generated by Django 5.0.7 on 2024-08-07 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0011_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_of_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
