# Generated by Django 5.0.7 on 2024-08-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0012_alter_contact_message_of_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
