# Generated by Django 5.1 on 2024-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0012_careersuggestion_suggested_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersuggestion",
            name="suggested_career",
            field=models.CharField(max_length=100),
        ),
    ]
