# Generated by Django 5.1 on 2024-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0013_alter_careersuggestion_suggested_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersuggestion",
            name="suggested_career",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
