# Generated by Django 5.0.7 on 2024-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0014_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=100),
        ),
    ]
