# Generated by Django 5.1 on 2024-09-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0014_alter_careersuggestion_suggested_career"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careersuggestion",
            name="suggested_career",
        ),
    ]
