# Generated by Django 5.1 on 2024-09-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0015_remove_careersuggestion_suggested_career"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CareerSuggestion",
        ),
    ]
