# Generated by Django 5.1 on 2024-09-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0016_delete_careersuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureCareer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operating_sys_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "algorithms_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "programming_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "software_eng_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "computer_network_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "electronics_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "computer_arc_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "math_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "communication_skills_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("coding_skills", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
