# Generated by Django 5.0.7 on 2024-08-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0016_customuser_department_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department_request',
        ),
        migrations.AddField(
            model_name='student',
            name='department_request',
            field=models.BooleanField(default=False),
        ),
    ]
