# Generated by Django 5.0.7 on 2024-08-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_delete_contact'),
        ('teacherapp', '0017_remove_customuser_department_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('grade_type', models.CharField(choices=[('AA', 4.0), ('BA', 3.7), ('BB', 3.3), ('CB', 3.0), ('CC', 2.7), ('DC', 2.3), ('DD', 2.0), ('FD', 1.7), ('FF', 0.0)], max_length=2)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student')),
            ],
        ),
    ]
