# Generated by Django 5.1 on 2024-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0018_futurecareer_suggested_career"),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureCareerSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification", models.CharField(max_length=100)),
                ("workshop", models.CharField(max_length=100)),
                ("interested_subjects", models.CharField(max_length=100)),
                ("interested_career_area", models.CharField(max_length=100)),
                ("company_type", models.CharField(max_length=100)),
                ("interested_books", models.CharField(max_length=100)),
                ("management_or_technical", models.CharField(max_length=100)),
                ("hard_or_smart_worker", models.CharField(max_length=100)),
                ("suggested_career", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="FutureCareer",
        ),
    ]
