# Generated by Django 5.0.7 on 2024-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0018_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='lesson',
            new_name='lesson_grade',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='student_grade',
        ),
    ]
