# Generated by Django 5.0.7 on 2024-08-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0019_rename_lesson_grade_lesson_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_grade',
            new_name='student',
        ),
    ]
