# Generated by Django 5.0.7 on 2024-08-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0021_remove_grade_grade_type_grade_grade_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_grade',
        ),
    ]
