# Generated by Django 5.0.7 on 2024-08-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0022_remove_student_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='lesson_grade',
            new_name='lesson',
        ),
    ]
