# Generated by Django 5.0.7 on 2024-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0023_rename_lesson_grade_grade_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_number',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[(4.0, 'AA'), (3.7, 'BA'), (3.3, 'BB'), (3.0, 'CB'), (2.7, 'CC'), (2.3, 'DC'), (2.0, 'DD'), (1.7, 'FD'), (0.0, 'FF')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
