# Generated by Django 5.0.7 on 2024-08-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0024_remove_grade_grade_number_grade_grade_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
    ]
