# Generated by Django 5.1 on 2024-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0029_alter_grade_grade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade",
            old_name="lesson",
            new_name="lesson_name",
        ),
        migrations.RenameField(
            model_name="grade",
            old_name="student",
            new_name="student_name",
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.FloatField(
                choices=[
                    (4.0, "AA"),
                    (3.5, "BA"),
                    (3.0, "BB"),
                    (2.5, "CB"),
                    (2.0, "CC"),
                    (1.5, "DC"),
                    (1.0, "DD"),
                    (0.5, "FD"),
                    (0.0, "FF"),
                ]
            ),
        ),
    ]
