# Generated by Django 5.1 on 2024-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacherapp", "0030_rename_lesson_grade_lesson_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade",
            old_name="lesson_name",
            new_name="lesson",
        ),
        migrations.RenameField(
            model_name="grade",
            old_name="student_name",
            new_name="student",
        ),
    ]
